provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  ocr-detect:
    lang: python3-http-debian
    handler: ./main
    image: localhost:5000/ocr-detect:latest
    build_args:
      ADDITIONAL_PACKAGE: "tesseract-ocr"
    environment:
      DIAGNOSTICS: "true"
      LOG_DIR: "/tmp/ocr_logs"
